name: Build Python wheels
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/manylinux2014_aarch64:latest
      WITH_TENSORFLOW: 
      PRE_CMD: 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch release tags from GitHub
        # Workaround for https://github.com/actions/checkout/issues/290
        run: git fetch --tags --force

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build wheels in a Docker image
        uese: addnab/docker-run-action@v3
        with:
          image: $DOCKER_IMAGE
          options: --rm -v `pwd`:/io --env WITH_TENSORFLOW=$WITH_TENSORFLOW
          run: |
              $PRE_CMD /io/travis/build_wheels$AARCH64.sh

      - name: Build sdist
        run: | 
          ls wheelhouse/
          sudo python setup.py sdist

      - name: Upload wheels and sdist
        uses: actions/upload-artifact@v2
        with:
          name: essentia-python-wheels
          path: |
            wheelhouse/essentia*.whl
            wheelhouse/essentia*.tar.gz
          if-no-files-found: error
