name: Build Python wheels
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch release tags from GitHub
        # Workaround for https://github.com/actions/checkout/issues/290
        run: git fetch --tags --force

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build wheels in a Docker image
        run: |
            docker manifest inspect --verbose ghcr.io/${{ github.repository_owner }}/manylinux2014_aarch64:latest
            docker run ghcr.io/${{ github.repository_owner }}/manylinux2014_aarch64:latest

      - name: Build sdist
        run: | 
          ls wheelhouse/
          sudo python setup.py sdist

      - name: Upload wheels and sdist
        uses: actions/upload-artifact@v2
        with:
          name: essentia-python-wheels
          path: |
            wheelhouse/essentia*.whl
            wheelhouse/essentia*.tar.gz
          if-no-files-found: error
